language: go

services:
  - docker

install:
  - go get -d -v ./...
  - go get github.com/mitchellh/gox

script:
  - make build tag push

after_success:
  - env
  - if [ "${TRAVIS_TAG}" != "" ] && [ "${TRAVIS_GO_VERSION}" == "1.7" ]; then gox -output "dist/{{.Dir}}-{{.OS}}-{{.Arch}}";fi

deploy:
  provider: releases
  api_key:
    secure: tlmTSb3AF4gQgPNiDkh1+6MnbXlMZFvYUaVP2PQP3zmSpGJ+Szwbck1e7s6WCeuxBG68FdgEoyjB4ScGEAiMeE40xAeQfupr/zKiW1FMh9Wviv9JjsUHuDG/rHL/wY5XdbOirWgbMCgcFQ+xoZvhtsm++F7v2vNQyObCqDbaQRNnl9SOf3+6egvKSHjzrVj94QGoILbjiRsOCM8G/xmF35uY7mrVqPia/Tocnp3sl2L6Z5EWDZTeMzBT2EmT1g7PYeOIxgVUo0WSZZgWQTdqr/yuVnwFZwlKlGrRY91XoI0/Q3LT7UeyCJcVABMw+P+OpzhWviBChRdcHmnE+zTDDBYYmnNHZNwWr+ts3Ps+5Y+f9gpMtRj+SCc8ktBQQQLwx78y0fckyq3V7D7XXp6Rc4Y1gco0WvEp10JICGyr+wWbGxD52OnjUlqmRoLjMAWYi1sqxeglRIQjqupO6HzTay1RziLQeZ7fJeShhkzNW5rlWyiMI/oCax/S7OZSPfCRafxI8jOjxzrkFGby1k6lfDMti4OIJpGr21tWaGRHk2dGctckUt5N+7oYwz3fwHY+bEyXk5Dk286AOqQYJPAOylpiW4obBnwJDNqqgckDizlGqUY0leFPYSQsHL/tIuK8RCYrooESRqOLITJGWmC85x6DRKVjXEWXM11RtymJIUg=
  file_glob: true
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true
